config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end
  root 'todo_lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
  belongs_to :user, optional: true , dependent: :destroy
  has_many :todo_items

  def has_completed_items?
    # code here
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :todo_lists, dependent: :destroy
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :todo_list
  before_action :todo_item, only: [:destroy]
  before_action :todo_item, except: [:create]

  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = 'Todo List item was deleted.'
    else
      flash[:error] = 'Todo List item could not be deleted.'
    end

    redirect_to @todo_list
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: 'Todo item completed'
  end

  private

  def todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  def todo_item_params
    params.require(:todo_item).permit(:content)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :todo_list, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  def index
    @todo_lists = TodoList.where(users_id: current_user.id)
  end

  def show; end

  def new
    @todo_list = TodoList.new
  end

  def edit; end

  def create
    @todo_list = TodoList.new(todo_list_params)
    @todo_list.users_id = current_user.id

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def todo_list
    @todo_list = TodoList.find(params[:id])
  end

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_form.html.haml
= form_for([@todo_list, @todo_list.todo_items.build]) do |f|
= f.text_field :content, placeholder: "New Todo"
= f.submit

app/views/layouts/_todo_item.html.haml
%p= todo_item.content

app/views/layouts/application.html.haml
!!!
%html
%head
%meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
%title App
= csrf_meta_tags
= csp_meta_tag
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
%link{:href => "http://fonts.googleapis.com/css?family=Lato:300,400,700", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css", :rel => "stylesheet"}/
%body
  = render 'shared/navbar'
%p.notice= notice
%p.alert= alert
= yield

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} Todo List App
  %button.navbar-toggler{"aria-controls" => "navbarText", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarText", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarText.collapse.navbar-collapse
    %ul.navbar-nav.mr-auto
    %span.navbar-text
      - if user_signed_in?
        = link_to "Logout", destroy_user_session_path, method: :delete
      - else
        = link_to "Login", new_user_session_path, data: {toggle: "modal", target: ".bd-example-modal-lg"}
        |
        \#{link_to "Sign Up", new_user_registration_path}

app/views/todo_items/_form.html.haml
= form_for([@todo_list, @todo_list.todo_items.build]) do |f|
  = f.text_field :content, placeholder: "New Todo"
  = f.submit

app/views/todo_items/_todo_item.html.haml
.row.clearfix
  - if todo_item.completed?
    .complete
      = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
        %i.fa.fa-check{:style => "opacity: 0.4;"}
    .todo_item
      %p{:style => "opacity: 0.4;"}
        %strike= todo_item.content
    .trash
      = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
        %i.fa.fa-trash
  - else
    .complete
      = link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do
        %i.fa.fa-circle-thin
    .todo_item
      %p= todo_item.content
    .trash
      = link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do
        %i.fa.fa-trash

app/views/todo_lists/_form.html.haml
= form_with(model: todo_list, local: true) do |form|
  - if todo_list.errors.any?
    #error_explanation
      %h2
        = pluralize(todo_list.errors.count, "error")
        prohibited this todo_list from being saved:
      %ul
        - todo_list.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :description
    = form.text_area :description
  .actions
    = form.submit

app/views/todo_lists/edit.html.haml
%h1.todo_list_title Editing Todo List
.forms
  = render 'form', todo_list: @todo_list
.links
  = link_to 'Cancel', todo_lists_path

app/views/todo_lists/index.html.haml
- @todo_lists.each do |todo_list|
  .index_row.clearfix
    %h2.todo_list_title= link_to todo_list.title, todo_list
    %p.todo_list_sub_title= todo_list.description
.links
  = link_to "New Todo List", new_todo_list_path

app/views/todo_lists/new.html.haml
%h1.todo_list_title New Todo List
.forms
  = render 'form', todo_list: @todo_list
.links
  = link_to 'Back', todo_lists_path

app/views/todo_lists/show.html.haml
%p#notice= notice
%h2.todo_list_title= @todo_list.title
%p.todo_list_sub_title= @todo_list.description
#todo_items_wrapper
  = render @todo_list.todo_items
  #form
    = render "todo_items/form"
.links
  = link_to 'Edit', edit_todo_list_path(@todo_list)
  = link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" }
  = link_to 'Back', todo_lists_path